const shelfList = [
    {
        'id': 1,
        'fileName': '2016_Book_PhysiologyPsychoacousticsAndCo',
        'cover': 'http://47.99.166.157/book/res/img/Biomedicine/978-3-319-25474-6_CoverFigure.jpg',
        'title': 'Physiology, Psychoacoustics and Cognition in Normal and Impaired Hearing',
        'author': 'Pim van Dijk',
        'publisher': 'Springer International Publishing',
        'bookId': '2016_Book_PhysiologyPsychoacousticsAndCo',
        'category': 12,
        'categoryText': 'Biomedicine',
        'language': 'en',
        'selected': false,
        'private': false,
        'cache': false,
        'haveRead': 0,
        'type': 1
    },
    {
        'id': 2,
        'fileName': '2017_Book_HormonesMetabolismAndTheBenefi',
        'cover': 'http://47.99.166.157/book/res/img/Biomedicine/978-3-319-72790-5_CoverFigure.jpg',
        'title': 'Hormones, Metabolism and the Benefits of Exercise',
        'author': 'Bruce Spiegelman',
        'publisher': 'Springer International Publishing',
        'bookId': '2017_Book_HormonesMetabolismAndTheBenefi',
        'category': 12,
        'categoryText': 'Biomedicine',
        'language': 'en',
        'selected': false,
        'private': false,
        'cache': false,
        'haveRead': 0,
        'type': 1
    },
    {
        'id': 3,
        'fileName': '2018_Book_NicotinicAcetylcholineReceptor',
        'cover': 'http://47.99.166.157/book/res/img/Biomedicine/978-981-10-8488-1_CoverFigure.jpg',
        'title': 'Nicotinic Acetylcholine Receptor Signaling in Neuroprotection',
        'author': 'Akinori Akaike',
        'publisher': 'Springer Singapore',
        'bookId': '2018_Book_NicotinicAcetylcholineReceptor',
        'category': 12,
        'categoryText': 'Biomedicine',
        'language': 'en',
        'selected': false,
        'private': false,
        'cache': false,
        'haveRead': 0,
        'type': 1
    },
    {
        'id': 4,
        'fileName': '2018_Book_Self-AssembledMoleculesNewKind',
        'cover': 'http://47.99.166.157/book/res/img/Biomedicine/978-3-319-65639-7_CoverFigure.jpg',
        'title': 'Self-Assembled Molecules – New Kind of Protein Ligands',
        'author': 'Irena Roterman',
        'publisher': 'Springer International Publishing',
        'bookId': '2018_Book_Self-AssembledMoleculesNewKind',
        'category': 12,
        'categoryText': 'Biomedicine',
        'language': 'en',
        'selected': false,
        'private': false,
        'cache': false,
        'haveRead': 0,
        'type': 1
    },
    {
        'id': 110,
        'fileName': '2014_Book_Self-ReportedPopulationHealthA',
        'cover': 'http://47.99.166.157/book/res/img/Biomedicine/2014_Book_Self-ReportedPopulationHealthA.jpeg',
        'title': 'Self-Reported Population Health: An International Perspective based on EQ-5D',
        'author': 'Agota Szende, Bas Janssen and Juan Cabasés',
        'publisher': 'Springer Netherlands, Dordrecht',
        'bookId': '2014_Book_Self-ReportedPopulationHealthA',
        'category': 12,
        'categoryText': 'Biomedicine',
        'language': 'en',
        'selected': false,
        'private': false,
        'cache': false,
        'haveRead': 0,
        'type': 1
    },
    {
        'id': 111,
        'fileName': '2015_Book_ContemporaryBioethics',
        'cover': 'http://47.99.166.157/book/res/img/Biomedicine/2015_Book_ContemporaryBioethics.jpeg',
        'title': 'Contemporary Bioethics',
        'author': 'Mohammed Ali Al-Bar and Hassan Chamsi-Pasha',
        'publisher': 'Springer International Publishing, Cham',
        'bookId': '2015_Book_ContemporaryBioethics',
        'category': 12,
        'categoryText': 'Biomedicine',
        'language': 'en',
        'selected': false,
        'private': false,
        'cache': false,
        'haveRead': 0,
        'type': 1
    },
    {
        'id': 112,
        'fileName': '2015_Book_HighDensityLipoproteins',
        'cover': 'http://47.99.166.157/book/res/img/Biomedicine/2015_Book_HighDensityLipoproteins.jpeg',
        'title': 'High Density Lipoproteins',
        'author': 'Arnold von Eckardstein and Dimitris Kardassis',
        'publisher': 'Springer International Publishing, Cham',
        'bookId': '2015_Book_HighDensityLipoproteins',
        'category': 12,
        'categoryText': 'Biomedicine',
        'language': 'en',
        'selected': false,
        'private': false,
        'cache': false,
        'haveRead': 0,
        'type': 1

    },
    {
        'id': 113,
        'fileName': '2015_Book_InnovativeMedicine',
        'cover': 'http://47.99.166.157/book/res/img/Biomedicine/2015_Book_InnovativeMedicine.jpeg',
        'title': 'Innovative Medicine',
        'author': 'Kazuwa Nakao, Nagahiro Minato and Shinji Uemoto',
        'publisher': 'Springer Japan, Tokyo',
        'bookId': '2015_Book_InnovativeMedicine',
        'category': 12,
        'categoryText': 'Biomedicine',
        'language': 'en',
        'selected': false,
        'private': false,
        'cache': false,
        'haveRead': 0,
        'type': 2
    },
    {
        'id': 114,
        'fileName': '2016_Book_ATimeForMetabolismAndHormones',
        'cover': 'http://47.99.166.157/book/res/img/Biomedicine/2016_Book_ATimeForMetabolismAndHormones.jpeg',
        'title': 'A Time for Metabolism and Hormones',
        'author': 'Paolo Sassone-Corsi and Yves Christen',
        'publisher': 'Springer International Publishing, Cham',
        'bookId': '2016_Book_ATimeForMetabolismAndHormones',
        'category': 12,
        'categoryText': 'Biomedicine',
        'language': 'en',
        'selected': false,
        'private': false,
        'cache': false,
        'haveRead': 0,
        'type': 2
    },
    {
        'id': 115,
        'fileName': '2016_Book_Micro-Meso-AndMacro-Connectomi',
        'cover': 'http://47.99.166.157/book/res/img/Biomedicine/2016_Book_Micro-Meso-AndMacro-Connectomi.jpeg',
        'title': 'Micro-, Meso- and Macro-Connectomics of the Brain',
        'author': 'Henry Kennedy, David C. Van Essen and Yves Christen',
        'publisher': 'Springer International Publishing, Cham',
        'bookId': '2016_Book_Micro-Meso-AndMacro-Connectomi',
        'category': 12,
        'categoryText': 'Biomedicine',
        'language': 'en',
        'selected': false,
        'private': false,
        'cache': false,
        'haveRead': 0,
        'type': 2
    },
    {
        'id': 116,
        'fileName': '2016_Book_Micro-Meso-AndMacro-DynamicsOf',
        'cover': 'http://47.99.166.157/book/res/img/Biomedicine/2016_Book_Micro-Meso-AndMacro-DynamicsOf.jpeg',
        'title': 'Micro-, Meso- and Macro-Dynamics of the Brain',
        'author': 'György Buzsáki and Yves Christen',
        'publisher': 'Springer International Publishing, Cham',
        'bookId': '2016_Book_Micro-Meso-AndMacro-DynamicsOf',
        'category': 12,
        'categoryText': 'Biomedicine',
        'language': 'en',
        'selected': false,
        'private': false,
        'cache': false,
        'haveRead': 0,
        'type': 2
    },
    {
        'id': 117,
        'fileName': '2016_Book_StemCellsInNeuroendocrinology',
        'cover': 'http://47.99.166.157/book/res/img/Biomedicine/2016_Book_StemCellsInNeuroendocrinology.jpeg',
        'title': 'Stem Cells in Neuroendocrinology',
        'author': 'Donald Pfaff and Yves Christen',
        'publisher': 'Springer International Publishing, Cham',
        'bookId': '2016_Book_StemCellsInNeuroendocrinology',
        'category': 12,
        'categoryText': 'Biomedicine',
        'language': 'en',
        'selected': false,
        'private': false,
        'cache': false,
        'haveRead': 0,
        'type': 2

    },
]
export default shelfList
